# Writing A DataFrame  To CSV
In this lesson we will discuss how you can save your data to csv.  This of course isn't the only way to write out or save data, but this is a common way, so we want to review it.

## Notebook Outline:
* [Using the .to_csv() method](#usingtocsv)

# Google Colab Path Note

If you run this notebook in Google Colab, mount Google Drive first:

```python
from google.colab import drive
drive.mount('/content/drive')
BASE_DIR = '/content/drive/MyDrive/Colab Notebooks/UCI/UCI_427.62_Python_for_Data_Analysis'
DATA_DIR = f'{BASE_DIR}/05_Datasets'
ASSIGNMENTS_DIR = f'{BASE_DIR}/04_Assignments'
OUTPUTS_DIR = f'{BASE_DIR}/04_Assignments/Outputs'
```

If you run locally in Jupyter/Anaconda, do not use `/content/drive`; use relative paths such as `../05_Datasets/...`.
The Mac path `/Users/yuzhang/.../My Drive/...` is only for local file browsing and is not a Colab path.

<a name=usingtocsv></a>
# Using the .to_csv() method
Writing a DataFrame to csv is simple, we just need to use the .to_csv() method. The documentation is here: <https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html>

In order to have an example, I am going to load the weather data that we have been using in this course. I am going to convert the celsius temperature to fahrenheit and then I am going to write out to a new file.

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

#### Load the data:

In [ ]:
# First we load the data, specifying the column names, like we saw in a previous
# lecture
filepath = ('/content/drive/MyDrive/Colab Notebooks/UCI/UCI_427.62_Python_for_Data_Analysis/05_Datasets/M1_724080-13739-2001')
headers = ['Year', 'Month', 'Day', 'Hour', 'Air Temp', 'Dew Point Temp', 'Sea Level Pressure',
           'Wind Direction', 'Wind Speed Rate',
           'Sky Condition Total Coverage Code',
           'Liquid Precipitation Depth Dimension - 1Hr Duration',
           'Liquid Precipitation Depth Dimension - Six Hour Duration']
weatherData = pd.read_csv(filepath, delim_whitespace=True,
                          names=headers)

/tmp/ipykernel_44148/4148507230.py:9: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  weatherData = pd.read_csv(filepath, delim_whitespace=True,

In [ ]:
weatherData.head()

,Year,Month,Day,Hour,Air Temp,Dew Point Temp,Sea Level Pressure,Wind Direction,Wind Speed Rate,Sky Condition Total Coverage Code,Liquid Precipitation Depth Dimension - 1Hr Duration,Liquid Precipitation Depth Dimension - Six Hour Duration
0,2022,1,1,0,80,80,10120,180,35,1,0,0
1,2022,1,1,1,85,80,10120,180,35,1,0,0
2,2022,1,1,2,90,80,10120,180,35,1,0,0
3,2022,1,1,3,95,80,10120,180,35,1,0,0
4,2022,1,1,4,100,80,10120,180,35,1,0,0

#### Convert the 'Air Temp' from Celsius to Fahrenheit

In [ ]:
# Now we will convert the Air Temp column to fahrenheit. First we need to divide
# the column by 10 (that is because the data is scaled by 10, i.e. -6 is really -0.6 celsius)
# this is covered in the data documentation discussed in a previous lecture.
# After dividing by 10, we convert from celsius to fahrenheit using the formula
# F = C * 1.8 + 32
weatherData.loc[:, 'Air Temp'] = (weatherData['Air Temp']/10) * 1.8 + 32

/tmp/ipykernel_44148/2258446482.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[46.4 47.3 48.2 49.1 50.  50.9 51.8 52.7 53.6 54.5 55.4 56.3 57.2 58.1
 59.  59.9 60.8 61.7 62.6 63.5 64.4 65.3 66.2 67.1 46.4 47.3 48.2 49.1
 50.  50.9 51.8 52.7 53.6 54.5 55.4 56.3 57.2 58.1 59.  59.9 60.8 61.7
 62.6 63.5 64.4 65.3 66.2 67.1 46.4 47.3 48.2 49.1 50.  50.9 51.8 52.7
 53.6 54.5 55.4 56.3 57.2 58.1 59.  59.9 60.8 61.7 62.6 63.5 64.4 65.3
 66.2 67.1]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  weatherData.loc[:, 'Air Temp'] = (weatherData['Air Temp']/10) * 1.8 + 32

In [ ]:
weatherData.head(2)

,Year,Month,Day,Hour,Air Temp,Dew Point Temp,Sea Level Pressure,Wind Direction,Wind Speed Rate,Sky Condition Total Coverage Code,Liquid Precipitation Depth Dimension - 1Hr Duration,Liquid Precipitation Depth Dimension - Six Hour Duration
0,2022,1,1,0,46.4,80,10120,180,35,1,0,0
1,2022,1,1,1,47.3,80,10120,180,35,1,0,0

#### Write the data to csv using .to_csv() - and use the index=False argument!

In [ ]:
savepath = ('/content/drive/MyDrive/Colab Notebooks/UCI/UCI_427.62_Python_for_Data_Analysis/05_Datasets/M1_724080-13739-2001_F')
weatherData.to_csv(savepath, index=False)

![](Success!.png)


---

# Additional Students Practice and Answer Key

These practice questions are designed for undergraduate students. Try the **Student Practice** cell first, then compare your work with the **Completed Answer** cell.

## Student Practice 1: Write a CSV File
Create a DataFrame with three rows and save it as `practice_students.csv`.

## Student Practice 2: Read the CSV Back
Read the file back into Python and display it.

In [ ]:
# Completed Answer: Write and Read CSV
import pandas as pd

df = pd.DataFrame({
    'student': ['A', 'B', 'C'],
    'score': [88, 76, 92]
})

df.to_csv('practice_students.csv', index=False)

loaded_df = pd.read_csv('practice_students.csv')
display(loaded_df)