# Setting Values In A DataFrame
## Notebook Outline:

* [Adding New Columns To A DataFrame](#AddNewColumns)
* [Updating Column Values](#UpdatingColumnValues)
* [Setting Specific Values](#SettingSpecificValues)

# Google Colab Path Note

If you run this notebook in Google Colab, mount Google Drive first:

```python
from google.colab import drive
drive.mount('/content/drive')
BASE_DIR = '/content/drive/MyDrive/Colab Notebooks/UCI/UCI_427.62_Python_for_Data_Analysis'
DATA_DIR = f'{BASE_DIR}/05_Datasets'
ASSIGNMENTS_DIR = f'{BASE_DIR}/04_Assignments'
OUTPUTS_DIR = f'{BASE_DIR}/04_Assignments/Outputs'
```

If you run locally in Jupyter/Anaconda, do not use `/content/drive`; use relative paths such as `../05_Datasets/...`.
The Mac path `/Users/yuzhang/.../My Drive/...` is only for local file browsing and is not a Colab path.

# How to use this Notebook

The best way to use this notebook is to follow along with the lecture and then to apply what you learn to your own data files, or (if you do not have any of your own data) to practice using this functions and methods on the provided data. A little practice goes a long way towards understand and retaining! It would be easy to just skim this notebook, but you will learn more by doing!

<a name='AddNewColumns'></a>
# Adding New Columns To A DataFrame
Adding new columns to a DataFrame is straightforward. We just need to use bracket notation, (without .loc or .iloc)
We need a dataset to practice on, so let's load the Philadelphia Airport Weather Dataset.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# In this cell we import pandas and load the datafile.
import pandas as pd
filepath = ('/content/drive/MyDrive/Colab Notebooks/UCI/UCI_427.62_Python_for_Data_Analysis/05_Datasets/M1_724080-13739-2001')
headers = ['Year', 'Month', 'Day', 'Hour', 'Air Temp', 'Dew Point Temp', 'Sea Level Pressure',
           'Wind Direction', 'Wind Speed Rate',
           'Sky Condition Total Coverage Code',
           'Liquid Precipitation Depth Dimension - 1Hr Duration',
           'Liquid Precipitation Depth Dimension - Six Hour Duration']
weatherData = pd.read_csv(filepath, delim_whitespace=True,
                          names=headers)

/tmp/ipykernel_682/1647663040.py:9: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  weatherData = pd.read_csv(filepath, delim_whitespace=True,

In [3]:
weatherData.head()

,Year,Month,Day,Hour,Air Temp,Dew Point Temp,Sea Level Pressure,Wind Direction,Wind Speed Rate,Sky Condition Total Coverage Code,Liquid Precipitation Depth Dimension - 1Hr Duration,Liquid Precipitation Depth Dimension - Six Hour Duration
0,2022,1,1,0,80,80,10120,180,35,1,0,0
1,2022,1,1,1,85,80,10120,180,35,1,0,0
2,2022,1,1,2,90,80,10120,180,35,1,0,0
3,2022,1,1,3,95,80,10120,180,35,1,0,0
4,2022,1,1,4,100,80,10120,180,35,1,0,0

#### Creating a copy of the Air Temp Column.
To do this, we will use the .loc method to select a _new_ column and set it equal to the airtemp column. Notice the new column at the end of the DataFrame after we complete this operation.

In [4]:
weatherData.loc[:, 'Air Temp Copy'] = weatherData['Air Temp']
weatherData.head()

,Year,Month,Day,Hour,Air Temp,Dew Point Temp,Sea Level Pressure,Wind Direction,Wind Speed Rate,Sky Condition Total Coverage Code,Liquid Precipitation Depth Dimension - 1Hr Duration,Liquid Precipitation Depth Dimension - Six Hour Duration,Air Temp Copy
0,2022,1,1,0,80,80,10120,180,35,1,0,0,80
1,2022,1,1,1,85,80,10120,180,35,1,0,0,85
2,2022,1,1,2,90,80,10120,180,35,1,0,0,90
3,2022,1,1,3,95,80,10120,180,35,1,0,0,95
4,2022,1,1,4,100,80,10120,180,35,1,0,0,100

<a name=UpdatingColumnValues></a>
# Updating Values of a DataFrame Column

#### Updating the Air Temp Column
This data actually need to be divided by 10 to be put in the proper decimal notation. That is, the -6 value is really -0.6 Celsius. This is described in the data documentation which can be found here <ftp://ftp.ncdc.noaa.gov/pub/data/noaa/isd-lite/isd-lite-format.pdf>

So, let's go ahead and update that column by dividing all the values by 10! We can do this with the same mathematical operators that we learned in the lecture on mathematical operators.

In [5]:
weatherData.loc[:, 'Air Temp'] = weatherData['Air Temp']/10
weatherData.head()

/tmp/ipykernel_682/1227982842.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5  8.   8.5  9.   9.5
 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5
 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5
 19.  19.5]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  weatherData.loc[:, 'Air Temp'] = weatherData['Air Temp']/10

,Year,Month,Day,Hour,Air Temp,Dew Point Temp,Sea Level Pressure,Wind Direction,Wind Speed Rate,Sky Condition Total Coverage Code,Liquid Precipitation Depth Dimension - 1Hr Duration,Liquid Precipitation Depth Dimension - Six Hour Duration,Air Temp Copy
0,2022,1,1,0,8.0,80,10120,180,35,1,0,0,80
1,2022,1,1,1,8.5,80,10120,180,35,1,0,0,85
2,2022,1,1,2,9.0,80,10120,180,35,1,0,0,90
3,2022,1,1,3,9.5,80,10120,180,35,1,0,0,95
4,2022,1,1,4,10.0,80,10120,180,35,1,0,0,100

#### Converting the Air Temp from Celsius to Fahrenheit - in a _new_ column
Now we will convert the Celsius air temp values to Fahrenheit values in a new column of data.

In [6]:
weatherData.loc[:, 'Air Temp F'] = weatherData['Air Temp'] * 1.8 + 32
weatherData.head()

,Year,Month,Day,Hour,Air Temp,Dew Point Temp,Sea Level Pressure,Wind Direction,Wind Speed Rate,Sky Condition Total Coverage Code,Liquid Precipitation Depth Dimension - 1Hr Duration,Liquid Precipitation Depth Dimension - Six Hour Duration,Air Temp Copy,Air Temp F
0,2022,1,1,0,8.0,80,10120,180,35,1,0,0,80,46.4
1,2022,1,1,1,8.5,80,10120,180,35,1,0,0,85,47.3
2,2022,1,1,2,9.0,80,10120,180,35,1,0,0,90,48.2
3,2022,1,1,3,9.5,80,10120,180,35,1,0,0,95,49.1
4,2022,1,1,4,10.0,80,10120,180,35,1,0,0,100,50.0

<a name=SettingSpecificValues></a>
# Setting Specific Values in a DataFrame

#### Changing the -9999 values to a Null value that Pandas will recognize.
We can use the .loc notation to set specific values in a column.  For example, let's change the -9999 values in the 'Liquid Precipitation Depth Dimension - Six Hour Duration' column to None values.

In [7]:
weatherData.loc[weatherData['Liquid Precipitation Depth Dimension - Six Hour Duration'] == -9999,
                'Liquid Precipitation Depth Dimension - Six Hour Duration'] = None
weatherData.head()

,Year,Month,Day,Hour,Air Temp,Dew Point Temp,Sea Level Pressure,Wind Direction,Wind Speed Rate,Sky Condition Total Coverage Code,Liquid Precipitation Depth Dimension - 1Hr Duration,Liquid Precipitation Depth Dimension - Six Hour Duration,Air Temp Copy,Air Temp F
0,2022,1,1,0,8.0,80,10120,180,35,1,0,0.0,80,46.4
1,2022,1,1,1,8.5,80,10120,180,35,1,0,0.0,85,47.3
2,2022,1,1,2,9.0,80,10120,180,35,1,0,0.0,90,48.2
3,2022,1,1,3,9.5,80,10120,180,35,1,0,0.0,95,49.1
4,2022,1,1,4,10.0,80,10120,180,35,1,0,0.0,100,50.0

#### Run .info() again to now see how many non-null values there are in 'Liquid Precipitation Depth Dimension - Six Hour Duration'

In [8]:
weatherData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 14 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   Year                                                      72 non-null     int64
 1   Month                                                     72 non-null     int64
 2   Day                                                       72 non-null     int64
 3   Hour                                                      72 non-null     int64
 4   Air Temp                                                  72 non-null     float64
 5   Dew Point Temp                                            72 non-null     int64
 6   Sea Level Pressure                                        72 non-null     int64
 7   Wind Direction                                            72 non-null     int64
 8   Wind Speed Rate                                           72 non-null     int64
 9   Sky Condition Total Coverage Code                         72 non-null     int64
 10  Liquid Precipitation Depth Dimension - 1Hr Duration       72 non-null     int64
 11  Liquid Precipitation Depth Dimension - Six Hour Duration  72 non-null     float64
 12  Air Temp Copy                                             72 non-null     int64
 13  Air Temp F                                                72 non-null     float64
dtypes: float64(3), int64(11)
memory usage: 8.0 KB

![](Success!.png)

# Lesson Summary:
In this lesson you learned:
* How to create new columns in a DataFrame.
* How to update the values of an entire column.
* How to update specific values in a DataFrame.